{
 "title": "PerfCI-Regression-Summary-Grafonnet",
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ocp_version",
    "query": "{\"find\":\"terms\",\"field\":\"ocp_version.keyword\"}"
   },
   {
    "name": "db_type",
    "query": "{\"find\":\"terms\",\"field\":\"db_type.keyword\"}"
   },
   {
    "name": "current_worker",
    "query": "{\"find\":\"terms\",\"field\":\"current_worker\"}"
   },
   {
    "name": "kind",
    "query": "{\"find\":\"terms\",\"field\":\"kind.keyword\"}"
   },
   {
    "name": "vdbench_type",
    "query": "{\"find\":\"terms\",\"field\":\"Run.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Workloads Legend",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "\n<p style=\"background-color:#000099;text-align: center;\" > > 100% new peak</p>\n<p style=\"background-color:#006600;text-align: center;color:black;\" > 90% - 100% of peak</p>\n<p style=\"background-color:#9fdf9f;text-align: center;color:black;\" > 80% -  90% of peak</p>\n<p style=\"background-color:#cc6600;text-align: center;color:black;\" > 50% -  80% of peak</p>\n<p style=\"background-color:#992600;text-align: center;\" > 0%  -  50% of peak</p>\n\n\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "![Cloud Governance](https://www.cielhr.com/wp-content/uploads/2019/10/PerformancewSpace-1080x675.png \"Tooltip Text\")\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product Versions",
   "type": "state-timeline",
   "description": "OVN - 09/19",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Openshift",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc[\"ocp_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\").replace(\"e\",\"1\").replace(\"c\",\"\").replace(\"r\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:ocp_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "CNV Nightly op.",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "(doc[\"cnv_version.keyword\"].value.indexOf(\" \") == -1) ? Integer.parseInt(\"0\"+doc[\"cnv_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\")) : 0"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:cnv_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "KATA op.",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "(doc[\"kata_version.keyword\"].value.indexOf(\" \") == -1) ? Integer.parseInt(doc[\"kata_version.keyword\"].value.replace(\".\",\"\")) : 0"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:kata_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "Kata rpm",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "Integer.parseInt(\"0\"+doc[\"kata_rpm_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\").replace(\"e\",\"1\").replace(\"c\",\"\").replace(\"r\",\"\"))"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:kata_rpm_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "ODF op.",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ci_minutes_time",
       "id": "1",
       "settings": {
        "script": "((doc[\"odf_version.keyword\"].size() != 0) ? ((doc[\"odf_version.keyword\"].value.indexOf(\" \") == -1) ? Integer.parseInt(\"0\"+doc[\"odf_version.keyword\"].value.replace(\".\",\"\").replace(\"r\",\"\").replace(\"c\",\"\").replace(\"f\",\"\").replace(\"-\",\"\")) : 0) : 0)"
       },
       "type": "max"
      }
     ],
     "query": "_exists_:odf_version AND ocp_version:$ocp_version",
     "timeField": "timestamp"
    },
    {
     "alias": "ODF # disks",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "odf_disk_count",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "ocp_version:$ocp_version",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Hammerdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HammerDB KTPM",
     "type": "state-timeline",
     "gridPos": { "h": 38, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "{{term db_type.keyword}}  : {{term current_worker}} threads : {{term kind.keyword}}:  {{term storage_type.keyword}}",
       "bucketAggs": [
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Uperf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uperf Latency (usecs)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "norm_ltcy",
         "id": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "_exists_:norm_ltcy AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1) AND test_type:rr AND norm_ltcy:<1000 AND kind:$kind  AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "norm_ltcy", "id": "1", "settings": { "script": "_value*8" }, "type": "avg" }
       ],
       "query": "_exists_:norm_ltcy AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(8) AND test_type:rr AND norm_ltcy:<1000 AND kind:$kind  AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf Throughput (Gbits/s)",
     "type": "state-timeline",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "alias": "msg size: {{term read_message_size}} :{{term num_threads}}th: {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
       ],
       "query": "_exists_:norm_ops AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:stream AND kind:$kind  AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Vdbench",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "vdbench (IOPS)",
     "type": "state-timeline",
     "gridPos": { "h": 48, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} Memory (GB) [384GB]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} %CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_CPU", "id": "1", "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th :{{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} Memory (GB) [384GB]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} %CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench Latency  (sec)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 50, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th : 1 {{term kind.keyword}}",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Resp", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "\"Total {{term kind.keyword}} Memory (GB) [384GB]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} %CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "!SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "{{term Run.keyword}} : {{term Threads}}th :{{term scale}} {{term kind.keyword}}s",
       "bucketAggs": [
        {
         "field": "Run.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Resp", "id": "1", "type": "avg" }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} Memory (GB) [384GB]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{term kind.keyword}} %CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "kind.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "SCALE AND !Run.keyword='fillup' AND kind:$kind AND Run:$vdbench_type AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusterbuster - Cpusoaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpusoaker",
     "type": "state-timeline",
     "description": "Higher is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 182 },
     "targets": [
      {
       "alias": "Max {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "test_description.pods", "id": "6", "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "CPU Iterations/sec {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_cpu_sec", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 192 },
     "targets": [
      {
       "alias": "Max {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "test_description.pods", "id": "6", "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 195 },
     "targets": [
      {
       "alias": "First start (sec) {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "first_pod_start", "id": "6", "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Last start (sec) {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "last_pod_start", "id": "6", "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "Memory (MB) {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "memory_per_pod", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusterbuster - FIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIO (IOPS/Throughtput)",
     "type": "state-timeline",
     "description": "Higher is better",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 183 },
     "targets": [
      {
       "alias": "read.iops: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.iops", "id": "6", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "write.iops: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "write.iops", "id": "6", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "total.iops: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total.iops", "id": "6", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "read.throughput: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.throughput", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "write.throughput: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "write.throughput", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "total.throughput: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "total.throughput", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusterbuster - Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Files (sec)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 184 },
     "targets": [
      {
       "alias": "create: 4096: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "create: 262,144:  {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "read : 4096: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "read : 262,144: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "remove : 4096: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "remove : 262,144: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.runtime.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.filesize:262144",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusterbuster - Uperf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uperf (Latency)",
     "type": "state-timeline",
     "description": "Lower is better",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 185 },
     "targets": [
      {
       "alias": "latency: {{term test_description.msgsize}}: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.msgsize",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "test_description.runtime.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "max_time_op", "id": "6", "settings": { "script": "_value*1000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf (Throughput)",
     "type": "state-timeline",
     "description": "Higher is better",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 194 },
     "targets": [
      {
       "alias": "rate: {{term test_description.msgsize}}: {{term test_description.runtime.keyword}}",
       "bucketAggs": [
        {
         "field": "test_description.msgsize",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "test_description.runtime.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "rate", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusterbuster - release",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "clusterbuster-cpusoaker [OVN - 09/19]",
     "type": "state-timeline",
     "description": "OVN - 09/19",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 261 },
     "targets": [
      {
       "alias": "pod: max",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "test_description.pods", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: max",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "test_description.pods", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: Memory per pod (MB)",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "memory_per_pod", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: Memory per kata  (MB)",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "memory_per_pod", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      },
      {
       "alias": "\"pod: start per seconds",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "pod_starts_per_second", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: start per seconds",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "pod_starts_per_second", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: Iteration cpu sec",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_cpu_sec", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: Iteration cpu sec",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_cpu_sec", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: Iteration sec",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_sec", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: Iteration sec",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "iterations_sec", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster-files: elapsed_time: Direct/ 64 dirs/files",
     "type": "state-timeline",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 297 },
     "targets": [
      {
       "alias": "pod: create: filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: create: filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: read :  filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: read:  filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: remove :  filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: remove:  filesize 4096",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:4096",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: create: filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: create:  filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "create.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: read :  filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: read :  filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "pod: remove :  filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc' and test_description.filesize:262144",
       "timeField": "timestamp"
      },
      {
       "alias": "kata: remove:  filesize 262,144",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "remove.elapsed_time", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata' and test_description.filesize:262144",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster-fio",
     "type": "state-timeline",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 333 },
     "targets": [
      {
       "alias": "runc read",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.iops", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata read",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "read.iops", "id": "6", "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster-uperf",
     "type": "state-timeline",
     "gridPos": { "h": 36, "w": 24, "x": 0, "y": 369 },
     "targets": [
      {
       "alias": "runc rate",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "rate", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='runc'",
       "timeField": "timestamp"
      },
      {
       "alias": "kata rate",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "rate", "id": "6", "settings": { "script": "_value/1000000" }, "type": "max" }
       ],
       "query": "test_description.runtime='kata'",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "BootStorm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "240 Fedora37 VMs(Sec)",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Min",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "min" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Max",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bootstorm_time",
         "id": "1",
         "settings": {
          "percents": [
           "25",
           "50",
           "75",
           "95",
           "99"
          ],
          "script": "_value/1000"
         },
         "type": "percentiles"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "AVG. 100 vms {{term node.keyword}}",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "node.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "avg" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory(GB) [384GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-0 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-0_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-1 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-1_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-2 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-2_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-0 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-0_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-1 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-1_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-2 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-2_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "VMs #",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "120 Windows Server 2019 VMs virtio (Sec)",
     "type": "state-timeline",
     "description": "Time till VM Login - Lower is better",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Min",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "min" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Max",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bootstorm_time",
         "id": "1",
         "settings": {
          "percents": [
           "25",
           "50",
           "75",
           "95",
           "99"
          ],
          "script": "_value/1000"
         },
         "type": "percentiles"
        }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "AVG. 40 vms {{term node.keyword}}",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "node.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bootstorm_time", "id": "1", "settings": { "script": "_value/1000" }, "type": "avg" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory(GB) [384GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "total_Memory", "id": "1", "settings": { "script": "_value/1000000000/2" }, "type": "max" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-0 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-0_Memory", "id": "1", "settings": { "script": "_value/1000000000" }, "type": "max" }
       ],
       "query": "scale:240 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-1 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-1_Memory", "id": "1", "settings": { "script": "_value/1000000000/2" }, "type": "max" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "Memory Worker-2 (GB) [128GB]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "worker-2_Memory", "id": "1", "settings": { "script": "_value/1000000000/2" }, "type": "max" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU [240 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "total_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-0 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-0_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-1 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-1_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "%CPU worker-2 [80 cores]",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "worker-2_CPU",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      },
      {
       "alias": "VMs #",
       "bucketAggs": [
        {
         "field": "scale",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "scale:120 AND ocp_version:$ocp_version",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Artifacts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HammerDB artifacts",
     "type": "table",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "db_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "current_worker",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "storage_type.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "tpm", "id": "1", "settings": { "script": "_value/1000" }, "type": "max" }
       ],
       "query": "_exists_:tpm AND db_type:$db_type AND current_worker:$current_worker AND kind:$kind",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Uperf artifacts",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "read_message_size",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "num_threads",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "norm_byte", "id": "1", "settings": { "script": "_value*8/1000000000" }, "type": "avg" }
       ],
       "query": "_exists_:norm_ops AND read_message_size:(64 OR 1024 OR 8192) AND num_threads:(1 OR 8) AND test_type:stream",
       "timeField": "uperf_ts"
      }
     ]
    },
    {
     "title": "vdbench artifacts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!SCALE AND !Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "vdbench scale artifacts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "Run.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Threads",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "!Run.keyword='fillup'",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster artifacts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "job_runtime",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "clusterbuster release artifacts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "job_runtime",
         "hide": false,
         "id": "1",
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "bootstorm artifacts",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "100",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "scale:240",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Windows artifacts",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ci_date.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "kind.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "scale",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "run_artifacts_url.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Rate", "id": "1", "type": "avg" }
       ],
       "query": "scale:120",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 107 },
     "options": {
      "content": "![Cloud Governance](https://github.com/redhat-performance/benchmark-runner/blob/main/media/benchmark_runner.png?raw=true \"Tooltip Text\")\n"
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}